@port = 5000
@baseURL = http://localhost:{{port}}/api
### GET /ads
GET {{baseURL}}/ads

### GET /ads/:id
GET  {{baseURL}}/ads/25


### POST /ads
POST  {{baseURL}}/ads/
content-type: application/json

{
	"title": "Mon titre XXsssssX",
	"description": "description",
	"price": 11,
	"owner" : "mon user",
	"picture": "http://placehold.it/32x32",
	"location": "nantes",
	"category": {"id" : 5}
}

### DELETE /ads/:id
DELETE  {{baseURL}}/ads/22

### PATCH /ads/:id
PATCH  {{baseURL}}/ads/25
content-type: application/json

{
	"title": "Mon titre sfffffff"
}

### GET category 
GET  {{baseURL}}/category/

### GET /category/:id
GET  {{baseURL}}/category/1

### GET /category/:id/ads recupere les annonces d'une categorie
GET http://localhost:3000/category/1/ads

### AJOUT category
POST http://localhost:3000/category/
content-type: application/json

{
	"name": "mobilier"
}



