### GET ROOT
GET http://localhost:3000/


### GET /ads
GET http://localhost:3000/ads


### POST /ads
POST http://localhost:3000/ads
content-type: application/json

{
	"title": "Titre 22323",
	"description": "description",
	"owner": "owner",
	"price": "price",
	"picture": "http://placehold.it/32x32",
	"location": "nantes",
	"category": "categoryA",
	"date": "20223-02-02"
}